############################################################
# This is a settings file for the Survival time by subgroup model.
# it contains the information necessary for lineup generation
# and plot illustration.
############################################################
app_settings = list()
app_settings$apptitle = "subgroupsurvival" # Title of app, to be displayed on top of analyze tab


### IMPORTS
library(xgxr)
library(survival)
library(survminer)
library(nullabor)

get_subgroup_survival_response_lineup <- function(data, input) {
	internal_data <- data.frame(groupname=data[,input$X], status=data[,input$Y], time=data[,input$t])
	
	return(nullabor::lineup(method = nullabor::null_permute("groupname"),
	                        true = internal_data,
	                        n = input$n_plots))
	#lineup(null_permute("groupname"), internal_data)
}

show_subgroup_survival_response_lineup <- function(lineup_data, input) {
  grouped_fits <- survminer::surv_fit(formula = Surv(time, status) ~ groupname,
                                      data = lineup_data, group.by = ".sample")
  splots <- list() # list to hold output of ggsurvplot
  ## survminer::ggsurvplot2 outputs a ggplot2 object and some additional stuff
  plots <- list() # ggsurvplot outputs a ggplot2 object & some additional data,
  for(i in 1:input$n_plots){
    
    tmp_fit <- grouped_fits[[i]]
    tmp_data <- lineup_data %>% filter(.sample == i)
    
    splots[[i]] <- 
      survminer::ggsurvplot(fit = tmp_fit,data = tmp_data,
                            linetype = 1,
                            legend = c(0.8, 0.75),
                            title = paste("Plot", i), 
                            ggtheme = theme(plot.title = element_text(size = 10, hjust = 0.5),
                                            axis.title = element_text(size = 10),
                                            axis.text = element_text(size = 10),
                                            legend.text = element_text(size = 8),
                                            legend.key.size = unit(3, "pt"),
                                            legend.title = element_text(size = 8),
                                            legend.background = element_rect(fill = "transparent", color = NA),
                                            plot.background = element_rect(fill='transparent')),
                            conf.int = TRUE)
    
    plots[[i]] <- splots[[i]][["plot"]]
  }
  return(plots)
  
  
  
	#km_fit <- survfit(Surv(time, status) ~ groupname, data = lineup_data, conf.int = 0.95)
	#gg <- ggsurvplot_facet(km_fit, lineup_data, facet.by = c(".sample"), conf.int = TRUE, 
	#                       ggtheme = xgx_theme(), short.panel.labs = TRUE, 
	#                       panel.labs = list(.sample = seq.int(1,20)))
	#gg <- gg + xgx_scale_x_time_units(units_dataset = "day", units_plot = "year")
	#gg
}

## COLUMN REGISTRATION
## This section is where you define the quantity that the user must register to columns in the uploaded dataset.
## For example, this may be the name of the independent, dependent, and covariate columns needed for this analysis.
## These columns are entered as 
## Ex: longname = c("Exposure", "Response") , shortname = ("X",:Y") 

app_settings$toRegister = data.frame(	
	"longname" = c("Group Label", "Status", "Time"),  # TODO 2: Create a list of display names of the quanity to register to columns.
	"shortname" = c("X", "Y", "t") # TODO 3: Create a corresponding list of shortname (must be valid variable names) for each longname.
)


## PLOT SETTING OPTIONS
## Create a list of toggle-able plot settings that will appear as options to the user.
## The list should map display names to the name of a function in R/setting_handler.R

app_settings$plotOptions = list() # TODO 4: Enter the toggled plot settings in the form of "display_name = function_name"


## ADDITIONAL SETTTINGS
## Define any additional settings that may be necessary. Do not include toggled plot settings, as those should go above.
## Currently server.R and ui.R do not use any other settings, so adding new settings functionality may will require changing those files.

app_settings$othersettings = list( 
  # TODO 5: add any additional settings that you may need elsewhere.
)


## LINEUP AND PLOT GENERATION FUNCTIONALITY
## Register lineup and plot generation functions
## The lineup generation function should take in a dataframe and return a
##    new dataframe with the same columns plus an additional .sample column
##    where the data frame contains 20 copies total of data, 1 of which is true
##    and 19 of which are generated by the null. See nullabor::lineup.
##
## The plot generation function should plot the dataframe returned by the lineup function
##    to show the null plots alongside the true plot. It should return a ggplot2 plot.

app_settings$lineup_generation_fn = get_subgroup_survival_response_lineup
app_settings$plot_generation_fn = show_subgroup_survival_response_lineup

## Preload
app_settings$preload_file = list("datapath"="vignette_data/fake_km_data.csv")
app_settings$toRegister$preload_columns = c("dose", "status", "time") 
app_settings$preload_plot_settings = c()