############################################################
# This is a settings file for the LONGTITLE model.
# it contains the information necessary for lineup generation
# and plot illustration.
############################################################
app_settings = list()
app_settings$apptitle = "Binary exposure - Binary response" # Title of app, to be displayed on top of analyze tab


### IMPORTS
# TODO 1: Add necessary imports


## COLUMN REGISTRATION
## This section is where you define the quantity that the user must register to columns in the uploaded dataset.
## For example, this may be the name of the independent, dependent, and covariate columns needed for this analysis.
## These columns are entered as 
## Ex: longname = c("Exposure", "Response") , shortname = ("X",:Y") 

app_settings$toRegister = data.frame(	
	"longname" = c("Arm", "Response"),  # TODO 2: Create a list of display names of the quanity to register to columns.
	"shortname" = c("X", "Y") # TODO 3: Create a corresponding list of shortname (must be valid variable names) for each longname.
)


## PLOT SETTING OPTIONS
## Create a list of toggle-able plot settings that will appear as options to the user.
## The list should map display names to the name of a function in R/setting_handler.R

app_settings$plotOptions = list() # TODO 4: Enter the toggled plot settings in the form of "display_name = function_name"


## ADDITIONAL SETTTINGS
## Define any additional settings that may be necessary. Do not include toggled plot settings, as those should go above.
## Currently server.R and ui.R do not use any other settings, so adding new settings functionality may will require changing those files.

app_settings$othersettings = list( 
  # TODO 5: add any additional settings that you may need elsewhere.
)


## LINEUP AND PLOT GENERATION FUNCTIONALITY
## Register lineup and plot generation functions
## The lineup generation function should take in a dataframe and return a
##    new dataframe with the same columns plus an additional .sample column
##    where the data frame contains 20 copies total of data, 1 of which is true
##    and 19 of which are generated by the null. See nullabor::lineup.
##
## The plot generation function should plot the dataframe returned by the lineup function
##    to show the null plots alongside the true plot. It should return a ggplot2 plot.

get_bin_exp_bin_resp_lineup <- function(data, input){
  lineup_data <- 
    data %>%
    rename(X = input$X,
           Y = input$Y) %>%
    nullabor::lineup(method = nullabor::null_permute("Y"),n = input$n_plots)
  return(lineup_data)
}
show_bin_exp_bin_resp_lineup <- function(lineup_data, input){
  
  plot_data <-
    lineup_data %>%
    group_by(.sample, X) %>%
    summarise(total = sum(Y),
              count = n(),
              avg = mean(Y)) %>%
    ungroup() %>%
    mutate(error = count * avg * (1 - avg),
           X = factor(X))
  
  ggplot(data = plot_data, mapping = aes(x = X, y = total, fill = X)) + 
    facet_wrap(~.sample) + 
    geom_bar(stat = "identity", color = "black", position = position_dodge(),
             width = 0.95) +
    geom_errorbar(aes(ymin = total, ymax = total + error), width = 0.2,
                  position = position_dodge(0.9)) + 
    xlab(input$X) + 
    ylab(input$Y) + 
    scale_fill_discrete(name = "Arm") + 
    theme_bw()
}


app_settings$lineup_generation_fn = get_bin_exp_bin_resp_lineup # TODO 6: Define a lineup generation function and reference it here
app_settings$plot_generation_fn = show_bin_exp_bin_resp_lineup# TODO 7: Define a plot generation function and reference it here.


## TODO 6: If there is an example vignette for the user to load, uncomment below and specify settings.
## Settings to specify inclues the data file, column registration information, and plot settings. 
## Effectively you are typing here what the user would have inputted into the left panel (settings).

#app_settings$preload_file = list("datapath"="...") # replace ... with your path.
#app_settings$toRegister$preload_columns =  c("...", "...") replace "..." with the corresponding column names being used. Follow the order specified in 'toRegister'.
#app_settings$preload_plot_settings = c(...) # add any plot settings that should be toggled on.