############################################################
# This is a settings file for the Linear Regression Multiple Comparison model.
# it contains the information necessary for lineup generation
# and plot illustration.
############################################################
library(nullabor)
library(grid)
library(gridExtra)
library(ggpubr)

app_settings = list()
app_settings$apptitle = "Linear Regression Multiple Comparison" # Title of app, to be displayed on top of analyze tab

get_linear_mc_lineup <- function(data, input) {
  N_row = 5
  IDseq_all = unique(data[input$IDseq])
  permute_one_id <- function(id) {
    datai = data %>% filter((!!sym(input$IDseq)) == id)
    null_permute(input$Y)(datai)
  }
  
  subgroup_null_permute <- function(data) {
    map_df(IDseq_all, permute_one_id)
  }
  
  lineup(subgroup_null_permute, data, n = N_row)
}

plot_sample <- function(sample_data, input) {
  N_top = 5
  
  IDseq_all = unique(sample_data$IDseq)
  regression_list = list()
  
  for (iseq in IDseq_all) {
    datai = sample_data %>% filter(IDseq == iseq)
    regression_list[[iseq]] = broom::tidy(lm(as.formula(paste(input$X, input$Y, sep="~")), data = datai)) %>%
      mutate(IDseq = iseq)
  }
  
  regression = bind_rows(regression_list) %>%
    filter(term == input$Y) %>%
    arrange(p.value)
  
  top = sample_data %>%
    ungroup() %>%
    filter(IDseq %in% regression$IDseq[1:N_top])  %>%
    mutate(IDseq_factor = factor(IDseq, levels = unique(IDseq))) #this is to plot in order of regression p value
  
  g = ggplot(top, aes_string(x = input$X, y = input$Y))
  g = g + geom_point()
  g = g + geom_smooth(method = "lm")
  g = g + facet_grid(cols=vars(IDseq), scales = "free_y")
  g = g + theme(axis.title.x=element_blank(),axis.title.y = element_blank())
  g
  row_number = toString(sample_data$.sample[1])
  
  row_label = grobTree(rectGrob(width=1.5, gp=gpar(fill="gray")),
                textGrob(row_number, gp=gpar(col="black", cex=1.2)))

  grobTree(rectGrob(gp=gpar(col="black")), arrangeGrob(g,left=row_label))
}


show_linear_mc_lineup <- function(lineup_data, input) {
	samples = unique(lineup_data$.sample)
	sample_id_to_plot <- function(sid) {
		sample_data = lineup_data %>% filter(.sample == sid)
		plot_sample(sample_data, input)
	}

	gs = lapply(samples, sample_id_to_plot)
	grd = ggarrange(plotlist=gs, ncol=1)
	grd
}


## COLUMN REGISTRATION
## This section is where you define the quantity that the user must register to columns in the uploaded dataset.
## For example, this may be the name of the independent, dependent, and covariate columns needed for this analysis.
## These columns are entered as 
## Ex: longname = c("Exposure", "Response") , shortname = ("X",:Y") 

app_settings$toRegister = data.frame(	
	"longname" = c("Exposure", "Response", "Subgroup"),  # TODO 2: Create a list of display names of the quanity to register to columns.
	"shortname" = c("X","Y","IDseq") # TODO 3: Create a corresponding list of shortname (must be valid variable names) for each longname.
)


## PLOT SETTING OPTIONS
## Create a list of toggle-able plot settings that will appear as options to the user.
## The list should map display names to the name of a function in R/setting_handler.R

app_settings$plotOptions = list() # TODO 4: Enter the toggled plot settings in the form of "display_name = function_name"


## ADDITIONAL SETTTINGS
## Define any additional settings that may be necessary. Do not include toggled plot settings, as those should go above.
## Currently server.R and ui.R do not use any other settings, so adding new settings functionality may will require changing those files.

app_settings$othersettings = list( 
  # TODO 5: add any additional settings that you may need elsewhere.
)


## LINEUP AND PLOT GENERATION FUNCTIONALITY
## Register lineup and plot generation functions
## The lineup generation function should take in a dataframe and return a
##    new dataframe with the same columns plus an additional .sample column
##    where the data frame contains 20 copies total of data, 1 of which is true
##    and 19 of which are generated by the null. See nullabor::lineup.
##
## The plot generation function should plot the dataframe returned by the lineup function
##    to show the null plots alongside the true plot. It should return a ggplot2 plot.






app_settings$lineup_generation_fn = get_linear_mc_lineup # TODO 6: Define a lineup generation function and reference it here
app_settings$plot_generation_fn = show_linear_mc_lineup # TODO 7: Define a plot generation function and reference it here.


## TODO 6: If there is an example vignette for the user to load, uncomment below and specify settings.
## Settings to specify inclues the data file, column registration information, and plot settings. 
## Effectively you are typing here what the user would have inputted into the left panel (settings).

app_settings$preload_file = list("datapath"="vignette_data/soma_mc_data.csv") # replace ... with your path.
app_settings$toRegister$preload_columns =  c("log10_PK", "log10_RFU", "IDseq") #replace "..." with the corresponding column names being used. Follow the order specified in 'toRegister'.
#app_settings$preload_plot_settings = c(...) # add any plot settings that should be toggled on.