---
title: Binary Outcome by Subgroup
output:
  html_document:
    theme: null
    highlight: null
    fig_retina: null
    fig_caption: true
    mathjax: default 
    keep_md: false
---


## Overview {#shinytab1}

This module is for analyzing occurrence rates of a binary outcome in different subgroups.
The module visually tests the null hypothesis
<center>
**The outcome occurs at the same rate within each subgroup.**
</center>
To use this module, you should upload a data table with at columns recording (i) the subgroup name or label; (ii) the total number of subjects in each subgroup; and (iii) the total number of outcome occurrences observed in each subgroup.  
Note that while the data must be uploaded in aggregated form (i.e. one row per subgroup), the module works by first disagreggating the data into a table in which there is one row per subject.
It then generates null datasets by permuting individuals' subgroup labels in the disaggregated datatable.
The module then plots the occurrence rate within each subgroup along with standard errors. 
The module generates null datasets by first expanding the supplied datatable 

permuting the entries in the exposure column while keeping the response column fixed.


## Example {#shinytab2}
<!-- SKD TO DO: write up the vignette for this analysis -->
