############################################################
# This is a settings file for the Binary response rate by subgroup model.
# it contains the information necessary for lineup generation
# and plot illustration.
############################################################
app_settings = list()
app_settings$apptitle = "subgroupbinary" # Title of app, to be displayed on top of analyze tab


### IMPORTS
library(nullabor)

get_subgroup_binary_response_lineup <- function(data, input, aggregate_data=FALSE) {

	# Aggregate out all other columns
	agg_data <- data.frame(groupname=data[,input$X], n=data[,input$n], N=data[,input$N])
	if (aggregate_data) {
		agg_data <- agg_data %>%
	  		group_by(groupname) %>%
	  		summarize(n = sum(n), N = sum(N))
	}

  	# Expand data set so that each row represents one individual
  	true_data <- NULL
	for (row in 1:nrow(agg_data)) {
		n_pos <- agg_data[row, input$n]
		n_neg <- agg_data[row, input$N] - n_pos
		row <- agg_data[row, ]

		drops <- c(input$n) # will remove successes count column once each row corresponds to one patient.

		if (n_pos > 0){
			positive_rows <- row[rep(1,n_pos),]
			positive_rows$outcome <- 1
			positive_rows <- positive_rows[ , !(names(positive_rows) %in% drops)]
			true_data <- dplyr::bind_rows(true_data, positive_rows)
		}

		if (n_neg){
			negative_rows <- row[rep(1,n_neg),]
			negative_rows$outcome <- 0
			negative_rows <- negative_rows[ , !(names(negative_rows) %in% drops)]
			true_data <- dplyr::bind_rows(true_data, negative_rows)
		}
	  
	}
	
	# Return to rows representing arms instead of individuals.
	lineup_data <- lineup(null_permute("outcome"), true_data)
	true <- attr(lineup_data, 'pos')
	lineup_data <- aggregate(list(n=rep(1,nrow(lineup_data))), lineup_data, length)
	lineup_data <- subset(lineup_data, outcome==1)
	lineup_data$p <- lineup_data$n / lineup_data$N
	attr(lineup_data, 'pos') <- true
	lineup_data

}

show_subgroup_binary_lineup <- function(lineup_data, input) {
	plt <- ggplot(data=lineup_data, aes_string(x="groupname", y="p")) +
		geom_point() +
		facet_wrap(~ .sample)
}

## COLUMN REGISTRATION
## This section is where you define the quantity that the user must register to columns in the uploaded dataset.
## For example, this may be the name of the independent, dependent, and covariate columns needed for this analysis.
## These columns are entered as 
## Ex: longname = c("Exposure", "Response") , shortname = ("X",:Y") 

app_settings$toRegister = data.frame(	
	"longname" = c("Arm Label", "Successes", "Total"),  # TODO 2: Create a list of display names of the quanity to register to columns.
	"shortname" = c("X", "n", "N") # TODO 3: Create a corresponding list of shortname (must be valid variable names) for each longname.
)


## PLOT SETTING OPTIONS
## Create a list of toggle-able plot settings that will appear as options to the user.
## The list should map display names to the name of a function in R/setting_handler.R

app_settings$plotOptions = list() # TODO 4: Enter the toggled plot settings in the form of "display_name = function_name"


## ADDITIONAL SETTTINGS
## Define any additional settings that may be necessary. Do not include toggled plot settings, as those should go above.
## Currently server.R and ui.R do not use any other settings, so adding new settings functionality may will require changing those files.

app_settings$othersettings = list( 
  # TODO 5: add any additional settings that you may need elsewhere.
)


## LINEUP AND PLOT GENERATION FUNCTIONALITY
## Register lineup and plot generation functions
## The lineup generation function should take in a dataframe and return a
##    new dataframe with the same columns plus an additional .sample column
##    where the data frame contains 20 copies total of data, 1 of which is true
##    and 19 of which are generated by the null. See nullabor::lineup.
##
## The plot generation function should plot the dataframe returned by the lineup function
##    to show the null plots alongside the true plot. It should return a ggplot2 plot.

app_settings$lineup_generation_fn = get_subgroup_binary_response_lineup
app_settings$plot_generation_fn = show_subgroup_binary_lineup


## Preload
app_settings$preload_file = list("datapath"="vignette_data/agrawal_16_table2.csv")
app_settings$toRegister$preload_columns = c("cancer", "n", "N") 
app_settings$preload_plot_settings = c()