############################################################
# This is a settings file for the LONGTITLE model.
# it contains the information necessary for lineup generation
# and plot illustration.
############################################################
app_settings = list()
app_settings$apptitle = "tornado" # Title of app, to be displayed on top of analyze tab


### IMPORTS
# TODO 1: Add necessary imports
library(ggplot2)


## COLUMN REGISTRATION
## This section is where you define the quantity that the user must register to columns in the uploaded dataset.
## For example, this may be the name of the independent, dependent, and covariate columns needed for this analysis.
## These columns are entered as 
## Ex: longname = c("Exposure", "Response") , shortname = ("X",:Y") 

app_settings$toRegister = data.frame(
  "longname" = c("Treatment"),
  "shortname" = c("treatment")
)


## PLOT SETTING OPTIONS
## Create a list of toggle-able plot settings that will appear as options to the user.
## The list should map display names to the name of a function in R/setting_handler.R

app_settings$plotOptions = list() # TODO 4: Enter the toggled plot settings in the form of "display_name = function_name"


## ADDITIONAL SETTTINGS
## Define any additional settings that may be necessary. Do not include toggled plot settings, as those should go above.
## Currently server.R and ui.R do not use any other settings, so adding new settings functionality may will require changing those files.

app_settings$othersettings = list( 
  # TODO 5: add any additional settings that you may need elsewhere.
)


## LINEUP AND PLOT GENERATION FUNCTIONALITY
## Register lineup and plot generation functions
## The lineup generation function should take in a dataframe and return a
##    new dataframe with the same columns plus an additional .sample column
##    where the data frame contains 20 copies total of data, 1 of which is true
##    and 19 of which are generated by the null. See nullabor::lineup.
##
## The plot generation function should plot the dataframe returned by the lineup function
##    to show the null plots alongside the true plot. It should return a ggplot2 plot.

get_tornado_lineup <- function(orig_data, input) {
  permuted_data <-
    orig_data %>%
    rename(treatment = input$treatment) %>%
    nullabor::lineup(method = nullabor::null_permute("treatment"), n = input$n_plots)
  return(permuted_data)
}


show_tornado_lineup <- function(lineup_data, input) {
  #lineup_data[,input$Z] <- factor(lineup_data[,input$Z])
  #ggplot(data=lineup_data, aes_string(x=input$X, y=input$Y, color=input$Z)) +
  #    facet_wrap(~ .sample) +
  #    geom_point() +
  #    scale_fill_discrete() 
  width <- 0.95
  plot_data <- 
    lineup_data %>%
    group_by(.sample, treatment) %>% # prepare to compute prevalence in each arm
    mutate_at(vars(-group_cols()), mean) %>% # computes the prevalence in each arm
    distinct() %>% # get rid of an duplicate rows
    ungroup() %>% # no longer need a grouping
    tidyr::pivot_longer(cols = -one_of(c("treatment", ".sample")),
                        names_to = "condition", values_to = "prop") %>%
    mutate(condition_num = as.numeric(factor(condition, levels = unique(condition))),
           arm = factor(treatment, levels = c(0,1), labels = c("Control", "Treated")),
           ymin = ifelse(treatment == 0, -1 * prop, 0),
           ymax = ifelse(treatment == 0, 0, 1 * prop),
           xmin = condition_num - width/2,
           xmax = condition_num + width/2)
    
  y_lim <- c(-1,1) * max(abs(c(plot_data$ymin, plot_data$ymax)))
  
  ggplot(data = plot_data) +
    facet_wrap(~.sample) + 
    scale_x_continuous(breaks = 1:length(unique(plot_data$condition)),
                       labels = unique(plot_data$condition)) +
    geom_rect(mapping = aes(ymax = ymax, ymin = ymin, xmin = xmin, xmax = xmax, fill = arm)) +
    #theme(panel.background = element_rect(fill = "white", color = "black")) + 
    theme_bw() + 
    ylim(y_lim) + 
    coord_flip() + 
    geom_hline(yintercept = 0)
}


app_settings$lineup_generation_fn = get_tornado_lineup # TODO 6: Define a lineup generation function and reference it here
app_settings$plot_generation_fn = show_tornado_lineup # TODO 7: Define a plot generation function and reference it here.


## TODO 6: If there is an example vignette for the user to load, uncomment below and specify settings.
## Settings to specify inclues the data file, column registration information, and plot settings. 
## Effectively you are typing here what the user would have inputted into the left panel (settings).

#app_settings$preload_file = list("datapath"="...") # replace ... with your path.
#app_settings$toRegister$preload_columns =  c("...", "...") replace "..." with the corresponding column names being used. Follow the order specified in 'toRegister'.
#app_settings$preload_plot_settings = c(...) # add any plot settings that should be toggled on.